<a href="https://colab.research.google.com/github/Dhanya-bhat/Application_of_Python_Programming_in_DA_and_ML/blob/master/Day3_Session2_Example_Programs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pandas Examples

Write a Pandas program to create and display a one-dimensional array using series  containing  even numbers upto 10


In [ ]:
import pandas as pd
#ds = pd.Series([2, 4, 6, 8, 10]) 
print(ds)

0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


Write a Pandas program to convert a Panda module Series to Python list and its type.

In [ ]:
import pandas as pd
ds = pd.Series([2, 4, 6, 8, 10])
print("Pandas Series and type")
print(ds)
print(type(ds))
print("Convert Pandas Series to Python list")
print(ds.tolist())
print(type(ds.tolist()))


Pandas Series and type
0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>
Convert Pandas Series to Python list
[2, 4, 6, 8, 10]
<class 'list'>


Write a Pandas program to add, subtract, multiple and divide two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]


In [ ]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)


Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


#Write a Pandas program to compare the elements of the two Pandas Series.
#Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]


In [ ]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 10])
print("Series1:")
print(ds1)
print("Series2:")
print(ds2)
print("Compare the elements of the said Series:")
print("Equals:")
print(ds1 == ds2)
print("Greater than:")
print(ds1 > ds2)
print("Less than:")
print(ds1 < ds2)



Series1:
0     2
1     4
2     6
3     8
4    10
dtype: int64
Series2:
0     1
1     3
2     5
3     7
4    10
dtype: int64
Compare the elements of the said Series:
Equals:
0    False
1    False
2    False
3    False
4     True
dtype: bool
Greater than:
0     True
1     True
2     True
3     True
4    False
dtype: bool
Less than:
0    False
1    False
2    False
3    False
4    False
dtype: bool


#Write a Pandas program to convert a dictionary to a Pandas series.
#Sample dictionary: d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800}


In [ ]:
import pandas as pd
d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800}
print("Original dictionary:")
print(d1)
new_series = pd.Series(d1)
print("Converted series:")
print(new_series)


Original dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
Converted series:
a    100
b    200
c    300
d    400
e    800
dtype: int64


#Write a Pandas program to convert a NumPy array to a Pandas series.
#Sample NumPy array: d1 = [10, 20, 30, 40, 50]


In [ ]:
import numpy as np
import pandas as pd
np_array = np.array([10, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)


NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64


#Write a Pandas program to change the data type of the given  Series into numeric
#['100', '200', 'python', '300.12', '400']


In [ ]:
import pandas as pd
s1 = pd.Series(['100', '200', 'python', '300.12', '400a'])
print("Original Data Series:")
print(s1)
print("Change the said data type to numeric:")
s2 = pd.to_numeric(s1, errors='coerce')
print(s2)


Original Data Series:
0       100
1       200
2    python
3    300.12
4      400a
dtype: object
Change the said data type to numeric:
0    100.00
1    200.00
2       NaN
3    300.12
4       NaN
dtype: float64


# Write a Pandas program to convert a given Series to an array.

In [ ]:
import numpy as np
s1 = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)


Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
Series to an array
['100' '200' 'python' '300.12' '400']


#Write a Pandas program to sort a given Series.

In [ ]:
import pandas as pd
s = pd.Series(['200','100','python', '300.12', '400'])
print("Original Data Series:")
print(s)
new_s = pd.Series(s).sort_values()
print(new_s)



Original Data Series:
0       200
1       100
2    python
3    300.12
4       400
dtype: object
1       100
0       200
3    300.12
4       400
2    python
dtype: object


#Write a Pandas program to add some data to an existing Series.

In [ ]:
import pandas as pd
s = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s)
print("\nData Series after adding some data:")
new_s = s.append(pd.Series(['500', 'php']))
print(new_s)


Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Data Series after adding some data:
0       100
1       200
2    python
3    300.12
4       400
0       500
1       php
dtype: object


#Write a Pandas program to create a subset of a given series based on value and condition.

In [ ]:
import pandas as pd
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n = 6
new_s = s[s >n]
print(new_s)


Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

Subset of the above Data Series:
7      7
8      8
9      9
10    10
dtype: int64


#Write a Pandas program to change the order of index of a given series.

In [ ]:
import pandas as pd
s = pd.Series(data = [1,2,3,4,5], index = ['A', 'B', 'C','D','E'])
print("Original Data Series:")
print(s)
s = s.reindex(index = ['B','A','C','D','E'])
print("Data Series after changing the order of index:")
print(s)


Original Data Series:
A    1
B    2
C    3
D    4
E    5
dtype: int64
Data Series after changing the order of index:
B    2
A    1
C    3
D    4
E    5
dtype: int64


#Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series.

In [ ]:
import pandas as pd
s = pd.Series(data = [1,2,3,4,5,6,7,8,9,5,3])
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())


Original Data Series:
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9     5
10    3
dtype: int64
Mean of the said Data Series:
4.818181818181818
Standard deviation of the said Data Series:
2.522624895547565


#Write a Pandas program to get the elements of an array values into column-wise.
#Sample data: {‘X’:[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}


In [ ]:
import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(df)


    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


#Write a Pandas program to get the columns of the DataFrame (movies_metadata.csv file).

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv('movies_metadata.csv')
print("Columns of the DataFrame:")
print(df.columns)



Columns of the DataFrame:
Index(['name', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am',
       'gear', 'carb'],
      dtype='object')


#Write a Pandas program to sort the DataFrame based on country from dataset of 
# movie_metadata.csv


In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv('movies_metadata.csv')
print("sorted by country")
small_df = df[['num_user_for_reviews','language','country','content_rating','budget','title_year']]
result = small_df.sort_values('country')
print("DataFrame based on release date.")
print(result)



#Write a Pandas program to get the details of the thrid movie of the DataFrame #(movie_metadata.csv file).

In [ ]:
import pandas as pd
df = pd.read_csv('movies_metadata.csv')
third_movie = df.iloc[2]
print("Details of the third moviee:")
print(third_movie)


Details of the third moviee:
name    Datsun 710
mpg           22.8
cyl              4
disp           108
hp              93
drat          3.85
wt            2.32
qsec         18.61
vs               1
am               1
gear             4
carb             1
Name: 2, dtype: object


#Write a Pandas program to display the first 10 rows of the DataFrame.

In [ ]:
import pandas as pd
df = pd.read_csv('movie_metadata.csv')
#Display the first 10 rows
result = df.head(10)
print("First 10 rows of the DataFrame:")
print(result)

Numpy Examples

#Write a NumPy program to generate five random numbers from the normal distribution.


In [ ]:
import numpy as np
x = np.random.normal(size=5)
print(x)


[-0.73484332 -2.06758974 -0.42557708  1.2968138   1.4552791 ]


#Write a NumPy program to generate six random integers between 10 and 30

In [ ]:
import numpy as np
x = np.random.randint(low=10, high=30, size=6)
print(x)


[29 12 11 14 21 19]


#Write a NumPy program to create a 3x3x3 array with random values

In [ ]:
import numpy as np
x = np.random.random((3,3,3))
print(x)


[[[0.99487735 0.60625752 0.12767563]
  [0.14247992 0.56553103 0.2649341 ]
  [0.30921218 0.25306467 0.0590202 ]]

 [[0.7203675  0.80142269 0.4099631 ]
  [0.23301769 0.18491438 0.79701086]
  [0.69266648 0.80946078 0.16679682]]

 [[0.36629437 0.96430302 0.01779249]
  [0.57060501 0.37709053 0.37284755]
  [0.00479387 0.5819956  0.66125106]]]


#Write a NumPy program to create a 5x5 array with random values and find the minimum #and maximum values.

In [ ]:
import numpy as np
x = np.random.random((5,5))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)


Original Array:
[[0.268411   0.65110316 0.74505169 0.67858868 0.12788649]
 [0.2104576  0.24421051 0.76203197 0.389655   0.02859948]
 [0.54179748 0.14756903 0.11719889 0.62904615 0.28841964]
 [0.0315095  0.09493423 0.61364028 0.71881946 0.72213014]
 [0.58050351 0.68820317 0.78540052 0.02553304 0.05474081]]
Minimum and Maximum Values:
0.0255330412818493 0.7854005179651231


#Write a NumPy program to create a random 10x4 array and extract the first five rows of the # array and store them into a variable.

In [ ]:
import numpy as np
x = np.random.rand(10, 4)
print("Original array: ")
print(x)
y= x[:5, :]
print("First 5 rows of the above array:")
y= x[:5, :]
print(y)
z= x[:, :4]
print("First 3 columns of the above array:")
print(z)



Original array: 
[[0.8438316  0.33133734 0.10827034 0.60587292]
 [0.99836023 0.12835129 0.34399752 0.3405714 ]
 [0.77876727 0.42287549 0.49141884 0.03650347]
 [0.05105686 0.21260386 0.14369151 0.67996685]
 [0.08773749 0.4437854  0.00493381 0.67100403]
 [0.47012345 0.67225777 0.00150105 0.73902107]
 [0.2459916  0.06414632 0.09016716 0.63882783]
 [0.89808954 0.23416089 0.66633577 0.54259273]
 [0.72629197 0.67198708 0.94530081 0.17102317]
 [0.98215293 0.91603302 0.60092954 0.47007975]]
First 5 rows of the above array:
[[0.8438316  0.33133734 0.10827034 0.60587292]
 [0.99836023 0.12835129 0.34399752 0.3405714 ]
 [0.77876727 0.42287549 0.49141884 0.03650347]
 [0.05105686 0.21260386 0.14369151 0.67996685]
 [0.08773749 0.4437854  0.00493381 0.67100403]]
First 3 columns of the above array:
[[0.8438316  0.33133734 0.10827034 0.60587292]
 [0.99836023 0.12835129 0.34399752 0.3405714 ]
 [0.77876727 0.42287549 0.49141884 0.03650347]
 [0.05105686 0.21260386 0.14369151 0.67996685]
 [0.08773749 0.4437

#Write a NumPy program to shuffle numbers and find permutation  between 0 and 10 #(inclusive).

In [ ]:
import numpy as np
x = np.arange(10)
np.random.shuffle(x)
print(x)
print("Same result using permutation():")
print(np.random.permutation(10))


[5 1 6 4 0 2 7 9 8 3]
Same result using permutation():
[2 6 7 3 4 8 9 0 5 1]


#Write a NumPy program to create a random integer nos of size 10 and sort it.

In [ ]:
import numpy as np
x=np.arange(10)
np.random.randint(x)
print (x)


ValueError: ignored

#Write a NumPy program to create a random integer nos of size 10 and sort it.

In [ ]:
import numpy as np
x=np.arange(10)
np.random.shuffle(x)
print(x)
x.sort()
print(x)


[3 8 5 9 7 2 4 6 0 1]
[0 1 2 3 4 5 6 7 8 9]
